### ISSUE TITLE
subdyn memberPostPro should include MJ output for segments with ID > 9

### ISSUE THREAD

**Issue by verlivkra** [ebranlard/welib#3]
When using the M1J1... output by setting OutAll = True in SubDyn, the number of members may be more than 9 (as opposed to NMOutputs <= 9). 

Suggest to update line #339 in subdyn.py 
from:

labels = [s[:4] for s in cols]

to e.g.: 

labels = [s.split('FK')[0].split('MK')[0].split('FM')[0].split('MM')[0] for s in cols]

**Comment by ebranlard** [comment]
Thanks for noticing that, I've pushed a fix for that.
